version: "3.7"

services:
  test:
    build: .
    depends_on:
      - mssql
    env_file:
      - .env.test
    networks:
      - db_proxy_test
    command: sh -c "set -o pipefail && wait-on -d 5000 -t 30000 tcp:mssql:1433 && node ./data/seed.mssql.mjs && TZ=UTC NODE_ENV=TEST node_modules/.bin/mocha"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_DATABASE=test
      - MSSQL_SLEEP=7
    volumes:
      - ./data/test_mssql.bak:/var/opt/mssql/backup/test.bak
    ports:
      - "1433:1433"
    networks:
      - db_proxy_test

networks:
  db_proxy_test:
    name: db_proxy_test
