version: "3.7"

services:
  test:
    env_file:
      - .env.secret

  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"

  mysql:
    ports:
      - "3306:3306"

  postgres:
    ports:
      - "5432:5432"